/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    AppFooter: typeof import('./src/components/shared/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/shared/AppHeader.vue')['default']
    CityTabs: typeof import('./src/components/CityTabs.vue')['default']
    CityView: typeof import('./src/views/CityView.vue')['default']
    FiveDaysForecast: typeof import('./src/components/cards/FiveDaysForecast.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    NextHoursForecast: typeof import('./src/components/cards/NextHoursForecast.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SearchCity: typeof import('./src/components/searchCity.vue')['default']
    WeatherCard: typeof import('./src/components/WeatherCard.vue')['default']
  }
}
